# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- dev

pool:
  name: 'Default'

steps:

- task: MGSonarQubePrepare@5
  inputs:
    SonarQube: 'Sona'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'ContributionManagementServer'
    cliSources: '.'
- task: MGSonarQubeAnalyze@5
- task: MGSonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'
