version: "3.3"
networks:
  dev:
    name: dev
services:
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - ${MONGODB_EXPRESS_PORT}:${MONGODB_EXPRESS_PORT}
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASS}
      ME_CONFIG_MONGODB_PORT: ${MONGODB_PORT}
      VCAP_APP_PORT: ${MONGODB_EXPRESS_PORT}
    depends_on:
      - mongo
    networks:
      - dev
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASS}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
      MONGODB_PORT: ${MONGODB_PORT}
      DB_NAME: ${MONGODB_DATABASE}
      DB_USER: ${MONGODB_USER}
      DB_PASSWORD: ${MONGODB_PASS}
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/mongo-init.sh
    command: --port ${MONGODB_PORT}
    networks:
      - dev
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}

  server:
#    extends:
#      file: docker-compose.yml
#      service: server
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT}
        reservations:
          memory: ${MEMORY_RESERVATIONS}
    image: contribution-management/server:dev
    user: "node:node"
    build:
      context: ../../
      dockerfile: Dockerfile
    command:
      - /bin/bash
      - -c
      - |
        ./wait-for-it.sh mongo:${MONGODB_PORT}
        npm run start-test
    volumes:
      - ../..:/app
      - /app/.env
      - /app/node_modules
    environment:
      - PROJECT_NAME
      - SERVER_SECRET
      - SERVER_PORT
      - MONGODB_URL
      - MONGODB_PORT
      - MONGODB_USER
      - MONGODB_PASS
      - MONGODB_DATABASE
      - API_PREFIX
      - CHECK_AUTH
      - CHECK_REQUEST_SIGNATURE
      - CHECK_CHANGE_PASSWORD
      - BLOCKCHAIN_URL
      - MAIL_NAME
      - PASSWORD
      - CHECK_BLOCKCHAIN
      - SEED_DATA
      - URL_PRODUCTION
      - TOTAL_QR
      - NUMBER_QR_PER_PAGE
      - CONCURRENT
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    depends_on:
      - mongo
    networks:
      - dev
    restart: always

